web/ViewComponents/NavbarVİewComponent/NavbarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using web.Data.Abstract;

namespace web.ViewComponents.NavbarViewComponent
{
    public class NavbarViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        public NavbarViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IViewComponentResult Invoke()
        {
            return View(_unitOfWork.Categories.GetAll());
        }
    }
}

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | GüzelSözSite</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/bootstrap/dist/css/bootstrap.min.css" />

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/8fdb1aed08.js" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Roboto:wght@100;300;400;500;700;900&display=swap"
        rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

    <!-- Site css -->
    <link rel="stylesheet" href="~/css/style.css" />
    @await RenderSectionAsync("Css",false)
</head>

<body>

    <header class="row">
        @* @await Html.PartialAsync("_logo") *@
        @await Component.InvokeAsync("Navbar")
        @await Html.PartialAsync("_headerbottom")
    </header>


    @if (IsSectionDefined("side"))
    {
        <div class="container bg-white">
            <div class="content row">
                <main class="col-9">

                    <section class="w-100 my-3">
                        @await Html.PartialAsync("_breadcrumb")
                    </section>

                    <section id="post" class="w-100 row">
                        @RenderBody()
                    </section>
                    <section id="related-post" class="w-100">
                        @await Html.PartialAsync("_related")
                    </section>
                    <section id="commentarea" class="w-100">
                        @await Component.InvokeAsync("Comments")
                    </section>
                </main>

                <aside class="col-3">
                    @RenderSection("side")
                </aside>
            </div>
        </div>
    }
    else
    {
        <div class="container">
            <main class="content row">
                @RenderBody()
            </main>
        </div>

    }
    <footer class="w-100 bg-dark text-white clearfix">
        <div class="w-33 float-start p-3">s</div>
        <div class="w-33 float-start p-3">s</div>
        <div class="w-33 float-start p-3">s</div>
        <div class="copyright w-100 px-5 py-3 float-start">
            <p>
                Copyright © 2022 Selçuk Şahin
            </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @* <script type="text/javascript" src="script.js"></script> *@
</body>

</html>

web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminPanel/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminPanel/dist/css/adminlte.min.css">
    <!-- Custom -->
    <link rel="stylesheet" href="~/AdminPanel/css/style.css">
    <!-- Data Table -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.5/datatables.min.css" />
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        @await Html.PartialAsync("Admin/_navbar.cshtml")
        @await Html.PartialAsync("Admin/_sidebar.cshtml")
        @* @await Component.InvokeAsync("Admin/Components/AdminSidebar") *@
        <div class="content-wrapper">

            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>@ViewData["PageTitle"]</h1>
                        </div>
                    </div>
                </div>
            </section>

            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </section>

        </div>

        <aside class="control-sidebar control-sidebar-dark">
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>


        @* @await Html.PartialAsync("Admin/_footer.cshtml") *@

    </div>

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Data table -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.5/datatables.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminPanel/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminPanel/dist/js/adminlte.min.js"></script>
    @RenderSection("Scripts",false)
</body>

</html>

web/Views/Shared/_alert.cshtml
@if (TempData["alert"] != null)
{
    var message = JsonConvert.DeserializeObject<AlertModel>(TempData["alert"] as String);
    <div class="alert alert-@message.Type alert-dismissible fade show" role="alert">
        <h5 class="alert-heading">@message.Title</h5>
        <hr class="my-2">
        @message.Message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

web/Views/Shared/_alertV4.cshtml
@if (TempData["alert"] != null)
{
    var message = JsonConvert.DeserializeObject<AlertModel>(TempData["alert"] as String);
    <div class="alert alert-@message.Type alert-dismissible fade show" role="alert">
        @message.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

web/Views/Shared/_breadcrumb.cshtml
@model PostDetailViewModel
<ol class="breadcrumb px-3 py-1">
    <li class="breadcrumb-item">
        <a href="/">Anasayfa</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="home" asp-action="category">Kategoriler</a>
    </li>
    <li class="breadcrumb-item">
        <a asp-controller="post" asp-action="postlist"
            asp-route-categoryurl="@Model.Category.CategoryUrl">@Model.Category.CategoryName</a>
    </li>
    <li class="breadcrumb-item active">
        <a>@Model.Post.PostTitle</a>
    </li>
</ol>

web/Views/Shared/_head.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | GüzelSözSite</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/bootstrap/dist/css/bootstrap.min.css" />

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/8fdb1aed08.js" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Roboto:wght@100;300;400;500;700;900&display=swap"
        rel="stylesheet">

    <!-- Site css -->
    <link rel="stylesheet" href="~/css/style.css" />

</head>

web/Views/Shared/_headerbottom.cshtml
<div class="header-bottom  bg-dark col-12 px-0">
    <div class="container clearfix">
        <div class="header-recommended w-75 float-start">
            <ul class="nav">
                <li class="nav-item">
                    <a asp-controller="home" asp-action="popular" class="nav-link">
                        <i class="fas fa-star"></i>
                        Popüler Kategoriler</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="home" asp-action="lastadded" class="nav-link">
                        <i class="fas fa-clock"></i>
                        Son Eklenenler</a>
                </li>
            </ul>
        </div>
        <div class="header-social w-25 float-start">
            <a href="#">
                <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
                <i class="fab fa-whatsapp"></i>
            </a>
        </div>
    </div>
</div>

web/Views/Shared/_latest.cshtml
<div class="section-title px-0">
    <h2>
        <span>Son Eklenenler</span>
    </h2>
</div>
<ul class="side-list">
    @foreach (var post in ViewBag.Latest)
    {
        <li class="side-list-item">
            <a href="/@post.Category.CategoryUrl/@post.PostUrl" class="w-100 clearfix">
                <div class="side-list-img w-25 float-start">
                    <img src="~/images/post/@post.PostImg" alt="">
                </div>
                <div class="side-list-info w-75 float-start ps-2">
                    <h2 class="side-list-title">@post.PostTitle</h2>
                    <p class="side-list-text">
                        @((post.PostSummary as String).Count()>100?
                    (post.PostSummary as String).Substring(0,100)+"...":post.PostSummary)
                    </p>
                </div>
            </a>
        </li>
    }
    <a asp-controller="home" asp-action="lastadded" class="more-btn mt-2">Devamını gör</a>
</ul>

web/Views/Shared/_logo.cshtml
<div class="col-12 py-2 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <a href="/">
                    <img src="https://picsum.photos/300/100" alt="" class="">
                </a>
            </div>
        </div>
    </div>
</div>

web/Views/Shared/_popular.cshtml
<div class="section-title px-0">
    <h2>
        <span>Popüler kategoriler</span>
    </h2>
</div>
<ul class="side-list">
    @foreach (var category in ViewBag.Popular)
    {
        <li class="side-list-item">
            <a href="/@category.CategoryUrl" class="w-100 clearfix">
                <div class="side-list-img w-25 float-start">
                    <img src="~/images/category/@category.CategoryImg" alt="">
                </div>
                <div class="side-list-info w-75 float-start ps-2">
                    <h2 class="side-list-title">@category.CategoryName</h2>
                    <p class="side-list-text"></p>
                </div>
            </a>
        </li>
    }
    <a asp-controller="home" asp-action="popular" class="more-btn mt-2">Devamını gör</a>
</ul>

web/Views/Shared/_related.cshtml
<h3 class="mb-3">Önerilen kategoriler <i class="far fa-thumbs-up"></i></h3>
<ul class="row row-cols-4 g-2">
    @foreach (var post in ViewBag.Related)
    {
        <li>
            <a href="/@post.Category.CategoryUrl/@post.PostUrl">
                <div class="card">
                    <img src="https://picsum.photos/600/300" class="card-img-top">
                    <div class="card-body p-2">
                        <h5 class="card-title fs-6 m-0">@post.PostTitle</h5>
                    </div>
                </div>
            </a>
        </li>
    }
</ul>
<hr>